#!/bin/bash
# Gradle wrapper-wrapper
# Prepare environment before invoking the actual Gradle wrapper

set -e
cd "$(dirname "$BASH_SOURCE")"

# Path of the output APK
apk=../virtualxposed.apk
unsigned_apk=app/build/outputs/apk/debug/app-debug.apk
# Key used to sign the APK
keystore=~/.android/debug.keystore
ndk_version=26.1.10909125

exposed_xposedapi_version=0.4.6
exposed_xposedapi_repo="XposedBridge/build/repo/me/weishu/exposed/exposed-xposedapi/$exposed_xposedapi_version"
exposed_xposedapi_pom="$exposed_xposedapi_repo/exposed-xposedapi-$exposed_xposedapi_version.pom"
exposed_xposedapi_artifact="$exposed_xposedapi_repo/exposed-xposedapi-$exposed_xposedapi_version.aar"

error () {
  echo [build] $* >&2
  return 1
}

# ANDROID_HOME, based on OS
export ANDROID_HOME
case "$(uname)" in
  Linux)
    : ${ANDROID_HOME:=$HOME/Android/Sdk} ;;
  Darwin)
    : ${ANDROID_HOME:=$HOME/Library/Android/sdk} ;;
esac

export ANDROID_NDK_HOME="$ANDROID_HOME/ndk/$ndk_version"

grep -q "android.ndkVersion=$ANDROID_NDK_HOME" local.properties 2> /dev/null ||
  echo "android.ndkVersion=$ANDROID_NDK_HOME" >> local.properties

[[ -d ~/.gradle ]] || mkdir ~/.gradle
[[ $(uname) != Darwin || $(uname -m) != arm64 ]] || {
  # Use protobuf on Apple Silicon
  grep -q 'protoc_platform=osx-x86_64' ~/.gradle/gradle.properties 2> /dev/null ||
    echo protoc_platform=osx-x86_64 >> ~/.gradle/gradle.properties
  # Use old NDK version on Apple Silicon
  [[ ! -f "$ANDROID_NDK_HOME/ndk-build" ]] ||
  grep -q 'arch -x86_64 /bin/bash $DIR/build/ndk-build "$@"' "$ANDROID_NDK_HOME/ndk-build" 2> /dev/null || {
    sed -i'' -e 's|^$DIR/build/ndk-build "$@"|# &|' "$ANDROID_NDK_HOME/ndk-build"
    echo 'arch -x86_64 /bin/bash $DIR/build/ndk-build "$@"' >> "$ANDROID_NDK_HOME/ndk-build"
  }
}

# Ensure the dependency 'exposed-xposedapi' is available in the local repo
# (the artifact has been removed from its official maven repository)
[[ -f "$exposed_xposedapi_pom" && -f "$exposed_xposedapi_artifact" ]] ||
  XposedBridge/gradleww

./gradlew -Pandroid.debug.obsoleteApi=true --warning-mode all "${@:-assembleDebug}"

# Create the keystore if it does not exist
[[ -f "$keystore" ]] ||
  keytool -genkey -v \
    -keystore "$keystore" \
    -storepass android \
    -alias androiddebugkey \
    -dname 'CN=Android Debug,O=Android,C=US' \
    -keypass android \
    -keyalg RSA \
    -keysize 2048 \
    -validity 10000

which apksigner &> /dev/null || {
  build_tools_version=$(ls "$ANDROID_HOME/build-tools" 2> /dev/null | tail -n 1 | grep '^\d*\.\d*\.\d*$') ||
    error No \`build-tools\` installed version found
  export PATH="$ANDROID_HOME/build-tools/$build_tools_version:$PATH"
}

apksigner sign --ks "$keystore" --ks-pass pass:android "$unsigned_apk"

# Move the apk outside of the app directory
cp "$unsigned_apk" "$apk"
